### ISSUE TITLE
 multiple import() statements on single line fails

### ISSUE THREAD

**Issue by MattiasJa** [morganney/magic-comments-loader#10]
Hi,
thanks for great tool!

I have a small issue with multiple import:s in the same file. The comments are only added to the first import when code is like:
```
reg( [
                { module: import('@pkg/button'), elem: 'Button' },
                { module: import('@pkg/collapse'), elem: 'Collapse' },
                { module: import('@pkg/icon'), elem: 'Icon' },
] );
```
The webpackChunkName func is only called once!

A work around is to move imports outside the object init :
```
const b = import('@pkg/button');
const c = import('@pkg/collapse');
const i = import('@pkg/icon');
reg( [
                { module: b, elem: 'Button' },
                { module: c, elem: 'Collapse' },
                { module: i, elem: 'Icon' },
] );
```
Now comments are added to all!

**Comment by morganney** [comment]
Thanks for pointing this out. I have to update some dependencies and tweak some documentation, so I'll put a fix in for this as well during the upcoming week. 

The issue is with the quotation character class (``['"`][^)$]*``) in the [negative lookbehind assertion to start the regex](https://github.com/morganney/magic-comments-loader/blob/master/src/util.js#L60). Might be time to pull in a parser for this package, we'll see :wink:.
